'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { BookOpen, House, Layers, MessageCircle, Volume2, Check, X, Clock3, Sparkles, Leaf, RotateCcw, Heart, GraduationCap, Headphones, PenLine, Mic, CalendarDays, ChevronLeft, Plus, LockKeyhole, Shuffle, Award, LogOut, UserRound } from 'lucide-react';
import { lessons, stages, lessonStage, lessonSteps, dateKey, plusDays, languages, languageNames, languageSymbols, locale, type Lang, type Lesson, type Phrase, type StudyState } from '@/lib/learning';

import BackupSettings from './backup-settings';
import WordPuzzle from './word-puzzle';
import VocabularyHub from './vocabulary-hub';
import {vocabulary,achievements} from '@/lib/vocabulary';

type View='home'|'path'|'review'|'growth'|'lesson'|'vocab'|'account';
type Session={lesson:Lesson;language:Lang;mode:'full'|'quick';step:number;id:string;started:number;quizCorrect:boolean};
const empty:StudyState={accountId:'',weeklyGoal:3,language:'en',today:dateKey(),sessions:[],completions:[],cards:[],words:[]};
const nav=[{id:'home',label:'Hôm nay',icon:House},{id:'path',label:'Hành trình',icon:BookOpen},{id:'vocab',label:'Túi từ',icon:Shuffle},{id:'review',label:'Ôn nhẹ',icon:Layers},{id:'growth',label:'Tiến bộ',icon:Leaf}] as const;

export default function LearningApp({account}:{account:{id:string;displayName:string;email:string;signOutUrl:string}}){
  const [view,setView]=useState<View>('home'),[language,setLanguage]=useState<Lang>('en'),[state,setState]=useState<StudyState>(empty);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[audioError,setAudioError]=useState('');
  const [session,setSession]=useState<Session|null>(null),[answer,setAnswer]=useState<number|null>(null),[revealed,setRevealed]=useState(false),[saved,setSaved]=useState(false),[earned,setEarned]=useState(0);
  const [selectedReview,setSelectedReview]=useState(0),[reviewReveal,setReviewReveal]=useState(false),[reviewCount,setReviewCount]=useState(0),[foundation,setFoundation]=useState<Lang|null>(null);
  const [selectedStage,setSelectedStage]=useState<number|null>(null);
  const requestBusy=useRef(false);
  const [accountChanged,setAccountChanged]=useState(false),[vocabIntent,setVocabIntent]=useState<'browse'|'play'|'review'>('browse');
  const rejectAccount=useCallback(()=>{setAccountChanged(true);setState(empty);setSession(null);},[]);
  const refresh=useCallback(async(initial=false)=>{if(requestBusy.current)return;requestBusy.current=true;setLoading(true);setError('');try {const r=await fetch('/api/progress',{cache:'no-store'});const d=await r.json() as StudyState & {error?:string};if(r.status===401){rejectAccount();return;}if(!r.ok)throw new Error(d.error);if(d.accountId!==account.id){rejectAccount();return;}setState(d);if(initial)setLanguage(d.language);}catch(e){setError(e instanceof Error?e.message:'Chưa tải được tiến bộ.');}finally{requestBusy.current=false;setLoading(false);}},[account.id,rejectAccount]);
  useEffect(()=>{void refresh(true);},[refresh]);
  useEffect(()=>{
    const check=()=>{if(document.visibilityState==='visible'&&!loading&&!busy&&!accountChanged)void refresh();};
    window.addEventListener('focus',check);document.addEventListener('visibilitychange',check);const timer=window.setInterval(()=>{if(dateKey()!==state.today)check();},60000);
    return()=>{window.removeEventListener('focus',check);document.removeEventListener('visibilitychange',check);window.clearInterval(timer);};
  },[state.today,loading,busy,refresh,accountChanged]);
  const mutate=useCallback(async(payload:Record<string,unknown>)=>{if(busy||loading||accountChanged||requestBusy.current)return null;requestBusy.current=true;setBusy(true);setError('');try{const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,accountId:account.id})});const d=await r.json() as StudyState & {error?:string;code?:string};if(r.status===401||d.code==='ACCOUNT_CHANGED'){rejectAccount();return null;}if(!r.ok)throw new Error(d.error);if(d.accountId!==account.id){rejectAccount();return null;}setState(d);return d as StudyState;}catch(e){setError(e instanceof Error?e.message:'Chưa lưu được. Hãy thử lại.');return null;}finally{requestBusy.current=false;setBusy(false);}},[account.id,accountChanged,busy,loading,rejectAccount]);
  function chooseLanguage(lang:Lang){if(busy||loading||accountChanged)return;setLanguage(lang);setFoundation(null);setSelectedStage(null);setSelectedReview(0);setReviewReveal(false);void mutate({action:'preferences',language:lang});}
  function navigate(v:View){setView(v);setAudioError('');if(typeof window!=='undefined' && 'speechSynthesis' in window)window.speechSynthesis.cancel();window.scrollTo({top:0,behavior:'smooth'});}
  function start(lesson:Lesson,mode:'full'|'quick'){
    if(loading||busy||accountChanged)return;
    setSession({lesson,language,mode,step:0,id:crypto.randomUUID(),started:Date.now(),quizCorrect:true});setAnswer(null);setSaved(false);setEarned(0);setAudioError('');navigate('lesson');
  }
  function advance(){setSession(s=>s?{...s,step:s.step+1}:null);setAnswer(null);setRevealed(false);setAudioError('');window.scrollTo({top:0,behavior:'smooth'});}
  function speak(text:string,lang:Lang=language){
    setAudioError('');if(!('speechSynthesis' in window)){setAudioError('Trình duyệt này chưa hỗ trợ đọc câu mẫu. Bạn vẫn có thể học bằng chữ.');return;}
    const synth=window.speechSynthesis;synth.cancel();const voices=synth.getVoices();
    const voice=voices.find(v=>v.lang.startsWith(locale[lang]))||voices.find(v=>v.lang.startsWith(lang));
    if(voices.length && !voice){setAudioError(`Thiết bị chưa có giọng ${languageNames[lang].toLowerCase()}. Thử mở bằng Chrome có giọng đọc phù hợp; bạn vẫn có thể học bằng chữ.`);return;}
    const utter=new SpeechSynthesisUtterance(text);utter.lang=locale[lang];utter.rate=lang==='zh'?0.72:0.8;if(voice)utter.voice=voice;
    utter.onerror=e=>{if(e.error!=='interrupted'&&e.error!=='canceled')setAudioError('Chưa phát được âm thanh. Hãy thử nghe lại.');};synth.speak(utter);
  }
  useEffect(()=>{if(!('speechSynthesis' in window))return;window.speechSynthesis.getVoices();return()=>window.speechSynthesis.cancel();},[]);
  const nextQuickLesson=lessons[language].find(l=>!state.cards.some(c=>c.language===language&&c.lesson_id===l.id&&c.phrase_index===0))||lessons[language][0];
  const completed=state.completions.filter(c=>c.language===language),nextLesson=lessons[language].find(l=>!completed.some(c=>c.lesson_id===l.id))||lessons[language][0];
  const courseTotal=lessons[language].length;
  const nextStage=lessonStage(nextLesson),activeStage=selectedStage??nextStage;
  const stageLessons=lessons[language].filter(l=>lessonStage(l)===activeStage);
  const stageCompleted=completed.filter(c=>stageLessons.some(l=>l.id===c.lesson_id)).length;
  const dialogue=session?(session.lesson.dialogue?.length?session.lesson.dialogue:[session.lesson.conversation]):[];
  const due=state.cards.filter(c=>c.language===language && c.due<=state.today),xp=state.sessions.reduce((n,s)=>n+s.xp,0),days=new Set(state.sessions.map(s=>s.day)).size;
  const todaySessions=state.sessions.filter(s=>s.day===state.today),hasToday=todaySessions.length>0;
  const lastDay=state.sessions[0]?.day,returning=lastDay && lastDay<plusDays(state.today,-1);
  const currentCard=due[selectedReview]||due[0],reviewLesson=currentCard?lessons[language].find(l=>l.id===currentCard.lesson_id):null,reviewPhrase=reviewLesson?.phrases[currentCard?.phrase_index||0];
  useEffect(()=>{setReviewReveal(false);},[language,currentCard?.lesson_id,currentCard?.phrase_index]);
  const totalLearned=state.cards.length;
  const metWords=state.words.filter(w=>w.learned===1).length;
  const wordDue=state.words.filter(w=>w.language===language&&w.learned===1&&w.due<=state.today).length;
  const badges=achievements(state);
  const weekDays=new Set(state.sessions.filter(s=>s.day>=plusDays(state.today,-6)&&s.day<=state.today).map(s=>s.day)).size;
  const gameToday=todaySessions.some(s=>s.language===language&&s.mode==='game');
  const reviewToday=todaySessions.some(s=>s.language===language&&(s.mode==='review'||s.mode==='vocab-review'));
  const nextLanguage:Lang=session?languages[(languages.indexOf(session.language)+1)%languages.length]:'en';
  function openVocabulary(intent:'browse'|'play'|'review'='browse'){setVocabIntent(intent);navigate('vocab');}
  function historyTitle(s:StudyState['sessions'][number]){return s.mode==='game'?'Ghép 5 cặp từ':s.mode==='vocab-review'?`Ôn từ: ${vocabulary[s.language].find(w=>w.id===s.lesson_id)?.term??''}`:lessons[s.language].find(l=>l.id===s.lesson_id)?.title??'Buổi học';}

  async function finish(){
    if(!session)return;const d=await mutate({action:'finish',id:session.id,language:session.language,lessonId:session.lesson.id,mode:session.mode,seconds:Math.min(3600,Math.round((Date.now()-session.started)/1000)),quizCorrect:session.quizCorrect});
    if(d){setEarned(d.sessions.find(s=>s.id===session.id)?.xp||0);setSaved(true);advance();}
  }
  async function review(remembered:boolean){if(!currentCard)return;const d=await mutate({action:'review',language,lessonId:currentCard.lesson_id,phraseIndex:currentCard.phrase_index,remembered,strength:currentCard.strength});if(d){setReviewCount(n=>n+1);setSelectedReview(0);setReviewReveal(false);}}
  const stepNames=session?lessonSteps(session.lesson,session.mode):[];
  const step=session?stepNames[session.step]:'';
  const talkIndex=step.startsWith('talk:')?Number(step.split(':')[1]):0;
  const turn=dialogue[talkIndex];
  const focusPhrase=session?.lesson.phrases[session.mode==='quick'?0:session.step<3?session.step:0];
  const renderPhrase=(phrase:Phrase,lang:Lang,small=false)=><div className={small?'phrase small':'phrase'}><p lang={locale[lang]}>{phrase.text}</p>{(phrase.pinyin||phrase.romaji)&&<span className="pinyin">{phrase.pinyin||phrase.romaji}</span>}<span className="meaning">{phrase.meaning}</span></div>;

  useEffect(()=>{
    const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
    if(!context?.registerTool)return;const lifecycle=new AbortController();
    const tools=[
      {name:'read_learning_progress',description:'Read the visible personal learning progress. Does not change progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');if(loading||error||accountChanged)throw new Error('Progress unavailable');return {language,learnedPhrases:totalLearned,completedLessons:state.completions.length,learningDays:days,xp,metWords,dueReviews:due.length+wordDue};}},
      {name:'start_next_language_lesson',description:'Open the next lesson in the selected language. Does not mark it complete.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['full','quick']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const a=input as {mode?:string};if(!a||!['full','quick'].includes(a.mode||'')||Object.keys(a).some(k=>k!=='mode'))throw new Error('Invalid lesson mode');if(busy||loading||accountChanged)throw new Error('Learning unavailable');start(a.mode==='quick'?nextQuickLesson:nextLesson,a.mode as 'full'|'quick');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {opened:true,lesson:(a.mode==='quick'?nextQuickLesson:nextLesson).title,language,mode:a.mode};}},
      {name:'open_vocabulary',description:'Open the visible vocabulary bank in the selected language. Does not change progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');if(loading||busy||accountChanged)throw new Error('Learning unavailable');openVocabulary();await new Promise(r=>requestAnimationFrame(r));return {opened:true,language,wordCount:vocabulary[language].length};}},
    ];
    for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return()=>lifecycle.abort();
  // The registry follows the same current state as the visible controls.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[state,language,loading,error,busy,accountChanged]);

  if(accountChanged)return <main className='account-changed'><UserRound size={35}/><h1>Mở lại góc học của bạn.</h1><p>Mở lại Mầm để vào đúng góc học và giữ tiến bộ riêng của bạn.</p><a className='primary ink' href='/'>Mở lại Mầm</a></main>;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="/" aria-label="Mầm, trang hôm nay"><span className="brand-mark">m</span><span>mầm<span className="brand-dot">.</span></span></a><div className="side-caption">MỖI NGÀY MỘT CHÚT</div>
      <nav aria-label="Điều hướng chính">{nav.map(({id,label,icon:Icon})=><button className={view===id||view==='lesson'&&id==='home'?'nav-item active':'nav-item'} key={id} onClick={()=>id==='vocab'?openVocabulary():navigate(id)}><Icon size={21}/>{label}{id==='review'&&due.length>0&&<span className="nav-badge">{due.length}</span>}</button>)}</nav>
      <div className="side-note"><Heart size={21}/><p>Nghỉ một hôm cũng ổn.<br/>Mầm vẫn ở đây.</p></div><div className="private"><LockKeyhole size={14}/> Không gian học riêng của bạn</div>
    </aside>
    <div className="main-wrap"><header className="topbar"><span className="crumb">{view==='lesson'?'Một bước nhỏ':view==='account'?'Tài khoản':nav.find(n=>n.id===view)?.label}</span><div className="top-actions"><span className="xp-pill"><Sparkles size={16}/>{xp} XP</span><button className="avatar" aria-label="Mở tài khoản của bạn" onClick={()=>navigate('account')}>{account.displayName.slice(0,1).toUpperCase()}</button></div></header>
    <main className="main-content">
      {error&&<div className="error" role="alert"><span>{error}</span><button onClick={()=>void refresh()} disabled={loading||busy}>Tải lại</button></div>}
      {view!=='lesson'&&<div className="language-switch" aria-label="Chọn ngôn ngữ">{languages.map(l=><button key={l} className={language===l?'selected':''} aria-pressed={language===l} disabled={busy||loading} onClick={()=>chooseLanguage(l)}><span className="lang-symbol">{languageSymbols[l]}</span>{languageNames[l]}</button>)}<span className="switch-note">Ba ngôn ngữ, theo nhịp của bạn.</span></div>}

      {view==='home'&&<>
        <div className="page-heading"><div><p className="eyebrow">{hasToday?'BẠN ĐÃ DÀNH THỜI GIAN CHO MÌNH':returning?'RẤT VUI VÌ BẠN QUAY LẠI':'CHÀO BẠN, BẮT ĐẦU NHẸ THÔI'}</p><h1>{hasToday?'Hôm nay, bạn đã tiến một chút.':returning?'Mình bắt đầu lại từ đây.':'Một chút hôm nay.\nMột câu nói ngày mai.'}</h1><p>{hasToday?'Học thêm nếu bạn muốn. Dừng ở đây cũng là đủ.':returning?'Không có bài học dồn hay thành tích bị trừ. Chỉ cần một câu.':'Không cần có động lực thật lớn. Chỉ cần thử một bài nhỏ.'}</p></div><div className="daily-stamp"><Clock3 size={19}/><strong>5 phút</strong><span>là một khởi đầu</span></div></div>
        <div className="home-grid"><section className="today-card"><div className="card-top"><span className="tag dark-tag">{stages[nextStage].label.toUpperCase()}{nextLesson.checkpoint?' · ÔN CHẶNG':''}</span><span className="lesson-number">{String(lessons[language].findIndex(l=>l.id===nextLesson.id)+1).padStart(2,'0')} / {String(courseTotal).padStart(2,'0')}</span></div><div className="hero-word" lang={locale[language]}>{nextLesson.phrases[0].text}</div>{(nextLesson.phrases[0].pinyin||nextLesson.phrases[0].romaji)&&<p className="hero-pinyin">{nextLesson.phrases[0].pinyin||nextLesson.phrases[0].romaji}</p>}<h2>{nextLesson.title}</h2><p>{nextLesson.context}</p>{nextLesson.focus&&<span className="focus-label">{nextLesson.focus}</span>}<div className="lesson-meta"><span><MessageCircle size={17}/>3 câu dùng được ngay</span><span><Headphones size={17}/>Nghe · thử nói</span></div><button className="primary ink" onClick={()=>session&&!saved&&session.language===language?navigate('lesson'):start(nextLesson,'full')}>{session&&!saved&&session.language===language?'Tiếp tục bài đang học':'Học bài này · khoảng 5 phút'}<BookOpen size={19}/></button></section>
        <div className="home-right"><section className="quick-card"><span className="mini-icon"><Heart size={21}/></span><h2>Hôm nay hơi mệt?</h2><p>Một câu, một phút.<br/>Vẫn tính là bạn đã có mặt.</p><button className="text-button" onClick={()=>start(nextQuickLesson,'quick')}>Học nhẹ 1 phút <Plus size={17}/></button></section><section className="review-peek"><div><span className="mini-icon purple"><Layers size={20}/></span><h2>{due.length?`${due.length} câu chờ bạn`:'Ôn một chút, nhớ lâu hơn'}</h2><p>{due.length?'Nhìn nghĩa, thử nhớ lại câu nói.':'Câu đã học sẽ quay lại đúng lúc.'}</p></div><button aria-label="Mở phần ôn nhẹ" className="round-button" onClick={()=>{setReviewCount(0);navigate('review');}}><RotateCcw size={21}/></button></section></div></div>
        <section className="daily-quests"><div className="section-title"><div><p className="eyebrow">MỘT VIỆC VỪA SỨC LÀ ĐỦ</p><h2>Hôm nay, thử một chút.</h2></div><span>Không cần làm hết.</span></div><div className="quest-grid"><button className={hasToday?'quest done':'quest'} disabled={busy||loading} onClick={()=>start(nextQuickLesson,'quick')}><span>{hasToday?<Check size={21}/>:<Heart size={21}/>}</span><strong>Có mặt hôm nay</strong><small>{hasToday?'Bạn đã dành thời gian cho mình.':'Một câu trong buổi nhẹ 1 phút.'}</small></button><button className={gameToday?'quest done':'quest'} disabled={busy||loading} onClick={()=>openVocabulary('play')}><span>{gameToday?<Check size={21}/>:<Shuffle size={21}/>}</span><strong>Gặp 5 từ nhỏ</strong><small>{gameToday?'Đã ghi nhận lượt chơi hôm nay.':'Thử ghép cặp từ với nghĩa.'}</small></button><button className={reviewToday?'quest done':'quest'} disabled={busy||loading||(!due.length&&!wordDue&&!reviewToday)} onClick={()=>due.length?navigate('review'):openVocabulary('review')}><span>{reviewToday?<Check size={21}/>:<Layers size={21}/>}</span><strong>Gặp lại một câu quen</strong><small>{reviewToday?'Bạn đã ôn một chút hôm nay.':due.length||wordDue?'Có câu hoặc từ đang đến lượt.':'Câu và từ đã gặp sẽ quay lại sau.'}</small></button></div></section>
        <div className="section-title"><h2>Những bước nhỏ của bạn</h2><button className="text-button" onClick={()=>navigate('growth')}>Xem tiến bộ</button></div><div className="stat-row"><div><span className="stat-icon"><CalendarDays size={21}/></span><div><strong>{loading?'…':days}<small> ngày đã học</small></strong><p>Mỗi lần quay lại đều đáng tính.</p></div></div><div><span className="stat-icon"><MessageCircle size={21}/></span><div><strong>{loading?'…':totalLearned}<small> câu đã gặp</small></strong><p>Góp từng câu cho giao tiếp.</p></div></div><div><span className="stat-icon"><Check size={21}/></span><div><strong>{loading?'…':state.completions.length}<small> bài trọn vẹn</small></strong><p>Buổi 1 phút cũng có XP riêng.</p></div></div></div>
        <section className="journey-strip"><span className="route-number">{String(nextStage+1).padStart(2,'0')}</span><div><p className="eyebrow">{language==='en'?'TỪ MẤT GỐC ĐẾN GIAO TIẾP':'TỪ CÂU ĐẦU TIÊN'}</p><h3>{stages[nextStage].name}</h3><p>{stages[nextStage].goal[language]}</p></div><button className="secondary" onClick={()=>navigate('path')}>Xem hành trình</button></section>
      </>}

      {view==='path'&&<><div className="page-heading compact"><div><p className="eyebrow">CÓ THỂ HỌC THEO BẤT KỲ THỨ TỰ NÀO</p><h1>Hành trình của bạn</h1><p>{completed.length}/{courseTotal} buổi {languageNames[language].toLowerCase()} đã hoàn thành. 30 buổi, không cần học trong đúng 30 ngày.</p></div></div><div className="stage-tabs" aria-label="Chọn chặng học">{stages.map((stage,i)=>{const items=lessons[language].filter(l=>lessonStage(l)===i);const count=completed.filter(c=>items.some(l=>l.id===c.lesson_id)).length;return <button key={stage.name} className={activeStage===i?'stage-card selected':'stage-card'} aria-pressed={activeStage===i} onClick={()=>setSelectedStage(i)}><span className="stage-top"><span>{stage.label}</span>{count===items.length&&items.length>0&&<Check size={17}/>}</span><strong>{stage.name}</strong><small>{count}/{items.length} buổi đã học</small><span className="stage-bar"><span style={{width:items.length?count/items.length*100+'%':0}}/></span></button>;})}</div><div className="stage-intro"><div><h2>{stages[activeStage].name}</h2><p>{stages[activeStage].goal[language]}</p></div><span className="tag">{stageCompleted}/{stageLessons.length} buổi</span></div><button className="foundation-card" onClick={()=>setFoundation(foundation===language?null:language)}><span className="foundation-symbol">{language==='en'?'Aa':language==='zh'?'拼':'あ'}</span><div><h2>{language==='en'?'Mất gốc? Ghé trạm nền tảng.':language==='zh'?'Làm quen pinyin & thanh điệu':'Làm quen kana & romaji'}</h2><p>{language==='en'?'Chữ cái, ghép câu và cách nói một nhu cầu.':language==='zh'?'Nghe trước, nhìn phiên âm, rồi thử nói chậm.':'Nhìn chữ, nghe mẫu và dùng romaji để bắt đầu.'}</p></div><span className="tag">{foundation===language?'Thu gọn':'Mở xem'}</span></button>
      {foundation&&<div className="foundation-details">{foundation==='en'?<><h3>Ba mẫu câu đầu tiên</h3><p>Tiếng Anh có 26 chữ cái. Đừng đợi thuộc hết mọi thứ mới nói: hãy dùng câu mẫu, rồi thay một từ.</p><div className="sample-grid">{[{text:'I am a student.',meaning:'Tôi là học sinh / sinh viên.'},{text:'I like coffee.',meaning:'Tôi thích cà phê.'},{text:'I need help.',meaning:'Tôi cần giúp đỡ.'}].map(p=><div key={p.text}>{renderPhrase(p,'en',true)}<button className="listen-button" onClick={()=>speak(p.text,'en')}><Volume2 size={17}/>Nghe mẫu</button></div>)}</div><p className="muted">“I” = tôi. “am” đi với “I” khi nói mình là ai. “like” = thích. “need” = cần. Chỉ cần thử nói một mẫu hôm nay.</p><button className="secondary" onClick={()=>speak('A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z','en')}><Volume2 size={17}/>Nghe tên 26 chữ cái</button></>:foundation==='zh'?<><h3>Cùng một “ma”, dấu khác nhau</h3><p>Pinyin là cách ghi âm tiếng Trung bằng chữ Latin. Dấu trên nguyên âm cho biết hướng đi của giọng.</p><div className="tone-grid">{[{text:'妈',pinyin:'mā',meaning:'Thanh 1: cao, ngang · mẹ'},{text:'麻',pinyin:'má',meaning:'Thanh 2: đi lên · cây gai'},{text:'马',pinyin:'mǎ',meaning:'Thanh 3: thấp rồi lên · ngựa'},{text:'骂',pinyin:'mà',meaning:'Thanh 4: đi xuống · mắng'}].map(p=><div key={p.text}>{renderPhrase(p,'zh',true)}<button className="listen-button" onClick={()=>speak(p.text,'zh')}><Volume2 size={17}/>Nghe</button></div>)}</div><p className="muted">Trong câu, thanh 3 thường chỉ đọc thấp; trước một thanh 3 khác, nó đọc gần thanh 2. Pinyin thường giữ dấu gốc, như nǐ hǎo; khi nói, 你好 đọc gần ní hǎo. 一 và 不 có thể đổi thanh theo âm đứng sau. Thanh nhẹ không có dấu và đọc ngắn.</p></>:<><h3>Đi từ năm âm đầu tiên.</h3><p>Tiếng Nhật dùng hiragana, katakana và kanji. Romaji là cách ghi âm bằng chữ Latin để bạn bắt đầu; mình sẽ làm quen chữ dần dần.</p><div className="kana-grid">{[{text:'あ',romaji:'a',meaning:'Âm a'},{text:'い',romaji:'i',meaning:'Âm i'},{text:'う',romaji:'u',meaning:'Âm u'},{text:'え',romaji:'e',meaning:'Âm e'},{text:'お',romaji:'o',meaning:'Âm o'}].map(p=><div key={p.text}>{renderPhrase(p,'ja',true)}<button className="listen-button" onClick={()=>speak(p.text,'ja')}><Volume2 size={17}/>Nghe</button></div>)}</div><p className="muted">Khi は làm trợ từ, nó thường đọc là wa: わたしは… (watashi wa…). Trường âm ō/ū trong romaji đọc dài hơn. Chưa cần thuộc toàn bộ bảng chữ mới dùng một lời chào.</p></>}</div>}
      <div className="lesson-list">{stageLessons.map((lesson)=>{const done=completed.some(c=>c.lesson_id===lesson.id);return <article className={done?'lesson-row completed':'lesson-row'} key={lesson.id}><span className="row-number">{done?<Check size={22}/>:String(lessons[language].findIndex(l=>l.id===lesson.id)+1).padStart(2,'0')}</span><div><h2>{lesson.title}</h2><p>{lesson.context}</p><span className="row-meta">{lesson.checkpoint?'Ôn chặng · ':''}{lesson.build?'Ghép câu · 2 lượt đáp':'3 câu'} · khoảng 5 phút{done?' · Đã học':''}</span>{lesson.focus&&<span className="row-focus">{lesson.focus}</span>}</div><button className="secondary" onClick={()=>start(lesson,'full')}>{done?'Học lại':'Mở bài'}</button></article>;})}</div>
      {language==='en'&&<section className="b1-panel"><span className="tag">ĐÍCH ĐẾN B1</span><h2>Nền tảng hôm nay, giao tiếp ngày mai.</h2><p>30 buổi tiếng Anh đi từ câu đầu tiên đến bài luyện nền tảng A1/A2: kể việc đã làm, lên kế hoạch và nêu lý do. Hoàn thành lộ trình chưa đồng nghĩa đạt B1; để thi VSTEP, bạn còn cần luyện đủ bốn kỹ năng theo định dạng đề thi.</p><div className="skill-grid">{[{icon:Headphones,title:'Nghe',text:'Từ câu ngắn đến ý chính của hội thoại.'},{icon:Mic,title:'Nói',text:'Giới thiệu bản thân, trao đổi và nêu ý kiến.'},{icon:BookOpen,title:'Đọc',text:'Hiểu thông báo, email và đoạn văn quen thuộc.'},{icon:PenLine,title:'Viết',text:'Từ câu đơn đến email và bài viết có bố cục.'}].map(({icon:Icon,title,text})=><div key={title}><Icon size={21}/><h3>{title}</h3><p>{text}</p></div>)}</div><p className="source-note">VSTEP 3–5: điểm trung bình 4,0–5,5 tương ứng Bậc 3/B1. <a href="https://www.is.vnu.edu.vn/gioi-thieu-mau-de-thi-va-tieu-chi-cham-bai-thi-vstep/" target="_blank" rel="noreferrer">Nguồn: Trường Quốc tế, ĐHQGHN</a>. Tiến bộ trong ứng dụng không quy đổi thành điểm thi.</p></section>}
      </>}

      {view==='review'&&<><div className="page-heading compact"><div><p className="eyebrow">QUÊN LÀ MỘT PHẦN CỦA VIỆC HỌC</p><h1>Gặp lại một câu quen.</h1><p>Thử nói từ nghĩa tiếng Việt, rồi mở câu mẫu để so sánh.</p></div><span className="tag">{due.length} câu đến lượt ôn</span></div>
      {reviewPhrase&&currentCard?<section className="exercise-card review-exercise"><span className="eyebrow">{reviewLesson?.title}</span><p className="review-meaning">{reviewPhrase.meaning}</p><p className="muted">Bạn sẽ nói câu này bằng {languageNames[language].toLowerCase()} như thế nào?</p>{reviewReveal?<><div className="review-answer">{renderPhrase(reviewPhrase,language)}</div><button className="listen-button" onClick={()=>speak(reviewPhrase.text)}><Volume2 size={20}/>Nghe mẫu</button><div className="review-actions"><button disabled={busy||loading} className="secondary" onClick={()=>void review(false)}>Chưa nhớ · gặp lại ngày mai</button><button disabled={busy||loading} className="primary" onClick={()=>void review(true)}><Check size={19}/>Mình nhớ rồi</button></div></>:<button className="primary" onClick={()=>setReviewReveal(true)}>Mở câu mẫu</button>}</section>:<section className="empty-card"><span className="empty-symbol"><Check size={36}/></span><h2>{reviewCount?'Bạn đã ôn xong lượt này.':'Hôm nay chưa có câu cần ôn.'}</h2><p>{state.cards.some(c=>c.language===language)?'Câu đã học sẽ quay lại theo nhịp nhớ: 1, 3, 7, 14 và 30 ngày.':'Học một bài, câu của bạn sẽ xuất hiện ở đây vào ngày mai.'}</p><button className="primary" onClick={()=>start(nextLesson,'full')}>Học một bài nhỏ</button></section>}
      <section className="review-peek"><div><span className="mini-icon purple"><Shuffle size={20}/></span><h2>{wordDue?`${wordDue} từ đến lượt ôn`:'Từ nhỏ cũng có nhịp ôn riêng'}</h2><p>{wordDue?'Thử nhớ từ đã gặp trong trò ghép cặp.':'Từ mới gặp trong trò chơi sẽ quay lại từ ngày mai.'}</p></div><button className="secondary" onClick={()=>openVocabulary('review')}>Mở phần ôn từ</button></section><div className="gentle-note"><Heart size={19}/><p>Không nhớ cũng không bị trừ điểm. Mầm chỉ đưa câu đó quay lại sớm hơn.</p></div></>}

      {view==='growth'&&<><div className="page-heading compact"><div><p className="eyebrow">KHÔNG CẦN MỘT CHUỖI NGÀY HOÀN HẢO</p><h1>Bạn đang đi tiếp.</h1><p>Thành tích đã có vẫn ở đây, kể cả khi bạn nghỉ.</p></div></div><div className="growth-hero"><div><Leaf size={31}/><p>BẠN ĐÃ TÍCH GÓP</p><strong>{xp}<span> XP</span></strong><p>{days} ngày đã học · {totalLearned} câu đã gặp</p></div><div className="level-note"><h2>{xp===0?'Bắt đầu bằng một câu.':xp<100?'Những bước đầu tiên.':xp<300?'Bạn đã có nhịp riêng.':'Từng chút đang thành nhiều.'}</h2><p>XP ghi nhận thời gian bạn có mặt, không đo trình độ ngoại ngữ.</p><div className="xp-track"><span style={{width:Math.min(100,xp%100|| (xp?100:0))+'%'}}/></div><small>Buổi 5 phút: 20 XP · buổi 1 phút: 5 XP.<br/>Học lại cùng bài, cùng chế độ trong ngày không cộng XP thêm.</small></div></div>
      <div className="section-title"><div><p className="eyebrow">KHÔNG PHẢI ĐIỂM THI</p><h2>Vườn thành tích nhỏ</h2></div><span className="muted">{badges.filter(b=>b.done).length}/{badges.length} dấu mốc</span></div><div className="badge-grid">{badges.map(b=><article className={b.done?'achievement earned':'achievement'} key={b.name}><span aria-hidden="true">{b.symbol}</span><h3>{b.name}</h3><p>{b.description}</p><small>{b.done?'Đã có trong vườn':'Khi nào vừa sức, mình thử tiếp'}</small></article>)}</div><div className="word-growth"><Shuffle size={24}/><div><strong>{metWords} từ đã gặp</strong><p>{state.words.filter(w=>w.favorite===1).length} từ yêu thích · {state.words.filter(w=>w.learned===1&&w.strength>=2).length} từ nhớ qua nhiều lượt ôn</p></div><button className="secondary" onClick={()=>openVocabulary()}>Mở túi từ</button></div>
      <section className="weekly-goal"><span className="weekly-icon"><Leaf size={27}/></span><div><p className="eyebrow">MỘT NHỊP NHẸ NHÀNG</p><h2>{weekDays>=state.weeklyGoal?'Bạn đã đạt nhịp học mình chọn.':`Thử có mặt trong ${state.weeklyGoal} ngày.`}</h2><p>{weekDays}/{state.weeklyGoal} ngày trong 7 ngày gần đây · một phút cũng được tính. Không cần học liền nhau.</p><div className="progress-track"><span style={{width:Math.min(100,weekDays/state.weeklyGoal*100)+'%'}}/></div><small>Ngày nghỉ không xóa những lần bạn đã có mặt.</small></div></section><div className="section-title"><h2>7 ngày gần đây</h2><span className="muted">Ngày nghỉ không xóa ngày đã học.</span></div><div className="week-grid">{Array.from({length:7},(_,i)=>plusDays(state.today,i-6)).map(day=>{const active=state.sessions.some(s=>s.day===day);return <div className={active?'week-day studied':'week-day'} key={day}><span>{new Intl.DateTimeFormat('vi-VN',{weekday:'short',timeZone:'UTC'}).format(new Date(day+'T00:00:00Z'))}</span><strong>{active?<Check size={23}/>:<span className="rest-mark">·</span>}</strong><small>{day.slice(8)}/{day.slice(5,7)}</small></div>;})}</div>
      <div className="section-title"><h2>Ba ngôn ngữ, từng bước nhỏ</h2></div><div className="language-progress">{languages.map(lang=>{const count=state.completions.filter(c=>c.language===lang).length;return <section key={lang}><span className="lang-symbol">{languageSymbols[lang]}</span><h3>{languageNames[lang]}</h3><span>{count}/{lessons[lang].length} buổi</span><div className="progress-track"><span style={{width:Math.min(100,count/lessons[lang].length*100)+'%'}}/></div><p>{state.cards.filter(c=>c.language===lang).length} câu đã gặp · {state.cards.filter(c=>c.language===lang&&c.strength>=2).length} câu nhớ qua nhiều lượt ôn</p></section>;})}</div>
      <div className="section-title"><h2>Các chặng bạn đã đi qua</h2></div><div className="milestone-grid">{stages.map((stage,i)=>{const items=lessons[language].filter(l=>lessonStage(l)===i);const count=completed.filter(c=>items.some(l=>l.id===c.lesson_id)).length;const done=items.length>0&&count===items.length;return <div className={done?'milestone done':'milestone'} key={stage.name}><span>{done?<Check size={22}/>:String(i+1).padStart(2,'0')}</span><h3>{stage.name}</h3><p>{count}/{items.length} buổi · {done?'Đã hoàn thành chặng':'Theo nhịp của bạn'}</p></div>;})}</div><div className="gentle-note"><Heart size={19}/><p>Chặng học ghi nhận bài bạn đã làm, không chứng nhận trình độ ngoại ngữ.</p></div><div className="section-title"><h2>Những lần bạn có mặt</h2></div>{state.sessions.length?<div className="history">{state.sessions.slice(0,10).map(s=><div key={s.id}><span className="history-icon"><Check size={18}/></span><div><strong>{historyTitle(s)}</strong><p>{languageNames[s.language]} · {s.mode==='quick'?'Buổi nhẹ 1 phút':s.mode==='review'?'Ôn nhẹ':s.mode==='game'?'Ghép cặp từ':s.mode==='vocab-review'?'Ôn từ vựng':'Bài đầy đủ'} · {s.day.split('-').reverse().join('/')}</p></div><span className="history-xp">+{s.xp} XP</span></div>)}</div>:<div className="gentle-note"><Sparkles size={20}/><p>Bài đầu tiên của bạn sẽ được ghi lại ở đây.</p></div>}</>}

      {view==='vocab'&&<VocabularyHub key={language+vocabIntent} intent={vocabIntent} language={language} state={state} busy={busy||loading} loading={loading} mutate={mutate} speak={speak}/>}
      {view==='account'&&<><div className="page-heading compact"><div><p className="eyebrow">GÓC HỌC CỦA RIÊNG BẠN</p><h1>Tài khoản học</h1><p>Mỗi tài khoản có tiến bộ, túi từ và lịch ôn riêng.</p></div></div><section className="account-card"><UserRound size={35}/><h2>{account.displayName}</h2><p>{account.email}</p><div className="account-stats"><span>{days} ngày đã học</span><span>{state.completions.length} bài trọn vẹn</span><span>{metWords} từ đã gặp</span></div><p className="muted">Đổi người học bằng cách đăng xuất rồi đăng nhập lại. Thành tích của bạn vẫn được giữ theo tài khoản này.</p><a className="secondary" href={account.signOutUrl} target="_top"><LogOut size={18}/>Đăng xuất khỏi Mầm</a></section><section className="account-card goal-settings"><CalendarDays size={28}/><h2>Một nhịp vừa sức</h2><p>Chọn số ngày muốn học trong 7 ngày gần đây. Một phút cũng được tính; ngày nghỉ không trừ thành tích.</p><label htmlFor="weekly-goal">Mục tiêu của mình</label><select id="weekly-goal" value={state.weeklyGoal} disabled={busy||loading} onChange={e=>void mutate({action:'goal',weeklyGoal:Number(e.target.value)})}>{Array.from({length:7},(_,i)=><option key={i+1} value={i+1}>{i+1} ngày trong 7 ngày</option>)}</select><small>Đã có mặt {weekDays} ngày trong 7 ngày gần đây.</small></section><BackupSettings state={state} busy={busy||loading} mutate={mutate}/></>}
      {view==='lesson'&&session&&<div className="lesson-workspace"><div className="lesson-toolbar"><button className="text-button" disabled={busy||loading} onClick={()=>navigate('home')}><ChevronLeft size={18}/>Tạm dừng</button><span>{languageNames[session.language]} · {session.mode==='quick'?'Buổi nhẹ 1 phút':'Khoảng 5 phút'}</span></div><div className="step-progress" aria-label={`Bước ${Math.min(session.step+1,stepNames.length-1)} trên ${stepNames.length-1}`}>{stepNames.slice(0,-1).map((_,i)=><span className={i<=session.step?'filled':''} key={i}/>)}</div>
      {step==='learn'&&focusPhrase&&<section className="exercise-card"><p className="eyebrow">{session.mode==='quick'?'MỘT CÂU LÀ ĐỦ':`LÀM QUEN · CÂU ${session.step+1} / 3`}</p><h1>{session.lesson.title}</h1><p className="exercise-context">{session.lesson.context}</p>{session.mode==='full'&&session.lesson.tip&&session.step===0&&<div className="language-tip"><strong>{session.lesson.focus}</strong><p>{session.lesson.tip}</p></div>}<div className="phrase-display">{renderPhrase(focusPhrase,session.language)}</div><button className="listen-button" onClick={()=>speak(focusPhrase.text,session.language)}><Volume2 size={21}/>Nghe chậm</button><p className="muted small-note">Nghe một lần, thử nói theo nếu bạn muốn.</p><button className="primary exercise-next" onClick={advance}>Mình đã xem câu này <Check size={19}/></button></section>}
      {(step==='quiz'||step==='quickquiz')&&(()=>{const q=step==='quickquiz'?{question:`“${session.lesson.phrases[0].text}” nghĩa là gì?`,options:session.lesson.phrases.map(p=>p.meaning),correctIndex:0,feedback:`${session.lesson.phrases[0].text} = ${session.lesson.phrases[0].meaning}`}:session.lesson.quiz;return <section className="exercise-card"><p className="eyebrow">THỬ NHỚ MỘT CHÚT</p><h1>{q.question}</h1><p className="muted">Chọn một câu trả lời. Sai cũng được học tiếp.</p><div className="answers">{q.options.map((option,i)=><button key={i} disabled={answer!==null} className={answer!==null&&i===q.correctIndex?'answer correct':answer===i?'answer incorrect':'answer'} onClick={()=>{setAnswer(i);if(i!==q.correctIndex)setSession({...session,quizCorrect:false});}}><span>{['A','B','C'][i]}</span>{option}{answer!==null&&i===q.correctIndex&&<Check size={20}/>}</button>)}</div>{answer!==null&&<div className={answer===q.correctIndex?'feedback success':'feedback'} role="status"><strong>{answer===q.correctIndex?'Đúng rồi!':'Không sao, mình gặp lại câu này nhé.'}</strong><p>{q.feedback}</p></div>}<button className="primary exercise-next" disabled={answer===null} onClick={advance}>Tiếp tục</button></section>;})()}
      {step==='build'&&session.lesson.build&&<WordPuzzle key={session.id} exercise={session.lesson.build} language={session.language} onContinue={advance}/> }
      {(step==='talk'||step.startsWith('talk:'))&&turn&&<section className="exercise-card"><p className="eyebrow">{dialogue.length>1?`HỘI THOẠI · LƯỢT ĐÁP ${talkIndex+1}/${dialogue.length}`:'MỘT CUỘC TRÒ CHUYỆN NHỎ'}</p><h1>Đến lượt bạn nói.</h1><p className="muted">{session.lesson.conversation.intro}</p>{talkIndex>0&&<div className="previous-reply"><span>Câu đáp mẫu ở lượt trước:</span><strong lang={locale[session.language]}>{dialogue[talkIndex-1].options[dialogue[talkIndex-1].correctIndex].text}</strong></div>}<div className="dialogue-bubble"><span className="speaker-label">NGƯỜI ĐỐI DIỆN</span>{renderPhrase(turn.speaker,session.language,true)}<button className="listen-button" onClick={()=>speak(turn.speaker.text,session.language)}><Volume2 size={18}/>Nghe câu hỏi</button></div><div className="answers reply-options">{turn.options.map((p,i)=><button disabled={answer!==null} className={answer!==null&&i===turn.correctIndex?'answer correct':answer===i?'answer incorrect':'answer'} key={i} onClick={()=>setAnswer(i)}><span className="answer-letter">{['A','B','C'][i]}</span><div lang={locale[session.language]}>{p.text}{(p.pinyin||p.romaji)&&<small>{p.pinyin||p.romaji}</small>}</div>{answer!==null&&i===turn.correctIndex&&<Check size={19}/>}</button>)}</div>{answer!==null&&<div className="feedback" role="status"><strong>{answer===turn.correctIndex?'Bạn đã đáp được rồi!':'Cùng xem cách đáp tự nhiên nhé.'}</strong><p>{turn.feedback}</p><p>{turn.options[turn.correctIndex].meaning}</p><button className="listen-button" onClick={()=>speak(turn.options[turn.correctIndex].text,session.language)}><Volume2 size={18}/>Nghe câu trả lời</button></div>}<button className="primary exercise-next" disabled={answer===null} onClick={advance}>Tiếp tục</button></section>}
      {step==='speak'&&<section className="exercise-card"><span className="speak-icon"><Mic size={30}/></span><p className="eyebrow">THỬ NÓI, NẾU BẠN MUỐN</p><h1>Mang câu này ra ngoài đời.</h1><p className="exercise-context">{session.mode==='quick'?'Thử nói câu vừa học một lần, thật chậm.':session.lesson.speak.prompt}</p><div className="phrase-display">{session.mode==='quick'?renderPhrase(session.lesson.phrases[0],session.language):<div className="phrase"><p lang={locale[session.language]}>{session.lesson.speak.text}</p>{(session.lesson.speak.pinyin||session.lesson.speak.romaji)&&<span className="pinyin">{session.lesson.speak.pinyin||session.lesson.speak.romaji}</span>}</div>}</div><button className="listen-button" onClick={()=>speak(session.mode==='quick'?session.lesson.phrases[0].text:session.lesson.speak.text,session.language)}><Volume2 size={20}/>Nghe để so sánh</button><p className="muted small-note">Bạn tự nghe và so sánh với mẫu. Phần này không ghi âm hay chấm phát âm.</p><button className="primary exercise-next" disabled={busy||loading} onClick={()=>void finish()}>{busy?'Đang lưu…':'Mình đã thử nói · hoàn thành'}<Check size={19}/></button><button className="text-button skip" disabled={busy||loading} onClick={()=>void finish()}>Để lần sau nói · vẫn hoàn thành</button></section>}
      {step==='done'&&saved&&<section className="exercise-card completion-card"><span className="completion-symbol"><Check size={44}/></span><p className="eyebrow">ĐÃ LƯU TIẾN BỘ CỦA BẠN</p><h1>Một chút cũng là tiến bộ.</h1><p>{session.mode==='quick'?'Bạn đã gặp một câu mới. Bài đầy đủ vẫn chờ khi bạn có năng lượng.':session.lesson.build?'Bạn đã học 3 câu, tự ghép một câu và đáp hai lượt hội thoại.':'Bạn đã học 3 câu và thử một tình huống giao tiếp.'}</p><div className="reward-pill"><Sparkles size={21}/>{earned>0?`+${earned} XP`:'Đã ghi nhận buổi ôn lại'}</div><div className="takeaway">{renderPhrase(session.lesson.phrases[0],session.language,true)}</div><p className="muted">Hôm nay như vậy là đủ. Câu đã học sẽ có lịch ôn riêng.</p><button className="primary exercise-next" onClick={()=>{setSession(null);navigate('home');}}>Xong cho hôm nay <Check size={19}/></button><button className="text-button skip" onClick={()=>{setSession(null);chooseLanguage(nextLanguage);navigate('home');}}>Muốn thêm một chút? Đổi sang {languageNames[nextLanguage].toLowerCase()}</button></section>}
      </div>}
      {audioError&&<div className="audio-note" role="status"><Volume2 size={18}/>{audioError}</div>}
      <footer className="footer"><span>mầm<span className="brand-dot">.</span></span><p>Học chậm một chút. Đi xa một chút.</p><span className="footer-private"><LockKeyhole size={13}/> Mầm v4</span></footer>
    </main></div>
  </div>;
}



