'use client';
import {useEffect,useState} from 'react';
import {Heart,Volume2,Shuffle,Check,ChevronLeft,Search,Layers} from 'lucide-react';
import {languageNames,locale,type Lang,type StudyState} from '@/lib/learning';
import {categories,vocabulary,type Vocabulary} from '@/lib/vocabulary';
type Props={language:Lang;state:StudyState;busy:boolean;loading:boolean;intent?:'browse'|'play'|'review';mutate:(payload:Record<string,unknown>)=>Promise<StudyState|null>;speak:(text:string,lang?:Lang)=>void};
function shuffle<T>(items:T[]){const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function searchText(text:string){return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');}
function newRound(items:Vocabulary[],progress:StudyState['words']){const unseen=items.filter(w=>!progress.some(p=>p.word_id===w.id&&p.learned===1));return {words:shuffle(unseen.length>=5?unseen:items).slice(0,5),id:crypto.randomUUID()};}

export default function VocabularyHub({language,state,busy,loading,mutate,speak,intent='browse'}:Props){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[filter,setFilter]=useState<'all'|'favorites'|'due'>(intent==='review'?'due':'all'),[detail,setDetail]=useState<string|null>(null),[revealed,setRevealed]=useState(false);
 const [game,setGame]=useState<{words:Vocabulary[];id:string}|null>(()=>intent==='play'?newRound(vocabulary[language],state.words):null);
 const progress=state.words.filter(w=>w.language===language);
 const due=progress.filter(w=>w.learned===1&&w.due<=state.today);
 const favorites=progress.filter(w=>w.favorite===1);
 const terms=vocabulary[language];
 const visible=terms.filter(w=>(category==='all'||w.category===category)&&(filter==='all'||(filter==='favorites'?favorites:due).some(p=>p.word_id===w.id))&&searchText(w.term+' '+w.meaning+' '+(w.reading??'')).includes(searchText(query)));
 const card=filter==='due'?visible[0]:null;
 const reviewProgress=card?due.find(p=>p.word_id===card.id):null;
 useEffect(()=>{setRevealed(false);},[card?.id]);
 function startGame(){
  setGame(newRound(visible,progress));
 }
 async function review(remembered:boolean){if(!card||!reviewProgress)return;const d=await mutate({action:'vocab_review',language,wordId:card.id,strength:reviewProgress.strength,remembered});if(d)setRevealed(false);}
 if(game)return <WordGame key={game.id} words={game.words} language={language} busy={busy||loading} speak={speak} onExit={()=>setGame(null)} onFinish={async(seconds)=>{const d=await mutate({action:'vocab_finish',language,id:game.id,wordIds:game.words.map(w=>w.id),seconds});return d?d.sessions.find(s=>s.id===game.id)?.xp??0:null;}}/>;
 return <>
  <div className="page-heading compact"><div><p className="eyebrow">TỪ NHỎ, CHUYỆN THƯỜNG NGÀY</p><h1>Túi từ của bạn</h1><p>{terms.length} từ & cụm từ {languageNames[language].toLowerCase()} · {progress.filter(w=>w.learned===1).length} từ đã gặp trong trò chơi.</p></div></div>
  <section className="vocab-play-card"><span className="mini-icon"><Shuffle size={23}/></span><div><h2>Ghép 5 cặp, gặp 5 từ.</h2><p>Xem mẫu trước, rồi thử ghép từ với nghĩa. Không đếm ngược, không mất lượt khi sai.</p><small>+5 XP cho lượt chơi đầu mỗi ngôn ngữ trong ngày.</small></div><button className="primary ink" disabled={busy||loading||visible.length<5} onClick={startGame}><Shuffle size={18}/>Chơi ghép cặp</button></section>
  <div className="vocab-toolbar"><label className="word-search"><Search size={19}/><input aria-label="Tìm từ hoặc nghĩa" placeholder="Tìm từ, phiên âm hoặc nghĩa…" value={query} onChange={e=>{setQuery(e.target.value);setRevealed(false);}}/></label><label className="category-select"><span>Chủ đề</span><select aria-label="Lọc chủ đề từ vựng" value={category} onChange={e=>{setCategory(e.target.value);setRevealed(false);}}><option value="all">Tất cả chủ đề</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
  <div className="vocab-tabs" aria-label="Bộ từ để xem">{[{id:'all',name:'Toàn bộ',count:terms.length},{id:'favorites',name:'Yêu thích',count:favorites.length},{id:'due',name:'Đến lượt ôn',count:due.length}].map(t=><button key={t.id} aria-pressed={filter===t.id} className={filter===t.id?'selected':''} onClick={()=>{setFilter(t.id as typeof filter);setRevealed(false);}}>{t.name}<span>{t.count}</span></button>)}</div>
  {filter==='due'&&(card?<section className="exercise-card word-review"><p className="eyebrow">THỬ NHỚ TỪ TIẾNG {languageNames[language].replace('Tiếng ','').toUpperCase()}</p><h2 className="review-meaning">{card.meaning}</h2><p className="muted">Bạn sẽ nói từ này như thế nào?</p>{revealed?<><div className="word-review-answer"><h3 lang={locale[language]}>{card.term}</h3>{card.reading&&<p className="pinyin">{card.reading}</p>}<p lang={locale[language]}>{card.example.text}</p>{card.example.reading&&<small>{card.example.reading}</small>}<p className="meaning">{card.example.meaning}</p></div><button className="listen-button" onClick={()=>speak(card.term,language)}><Volume2 size={18}/>Nghe từ</button><div className="review-actions"><button disabled={busy||loading} className="secondary" onClick={()=>void review(false)}>Chưa nhớ · gặp lại ngày mai</button><button disabled={busy||loading} className="primary" onClick={()=>void review(true)}>Mình nhớ rồi <Check size={18}/></button></div></>:<button className="primary exercise-next" onClick={()=>setRevealed(true)}>Mở từ mẫu</button>}</section>:<div className="gentle-note"><Layers size={22}/><p>Chưa có từ đến lượt ôn trong bộ lọc này. Từ mới gặp trong trò chơi có lịch ôn ngày mai; các từ đã luyện quay lại theo nhịp nhớ.</p></div>)}
  {filter!=='due'&&<><p className="vocab-results">{visible.length} mục{visible.length>0&&visible.length<5?' · cần ít nhất 5 mục để chơi ghép cặp':''}</p><div className="word-grid">{visible.map(w=>{const favorite=favorites.some(p=>p.word_id===w.id);return <article className="word-card" key={w.id}><div className="word-card-top"><span>{categories.find(c=>c.id===w.category)?.name}</span><button className={favorite?'word-heart selected':'word-heart'} disabled={busy||loading} aria-label={`${favorite?'Bỏ lưu':'Lưu'} từ ${w.term}`} aria-pressed={favorite} onClick={()=>void mutate({action:'vocab_favorite',language,wordId:w.id,favorite:!favorite})}><Heart size={18} fill={favorite?'currentColor':'none'}/></button></div><h2 lang={locale[language]}>{w.term}</h2>{w.reading&&<p className="word-reading">{w.reading}</p>}<p className="word-meaning">{w.meaning}</p><div className="word-actions"><button className="listen-button" aria-label={`Nghe từ ${w.term}`} onClick={()=>speak(w.term,language)}><Volume2 size={17}/>Nghe</button><button className="text-button" aria-expanded={detail===w.id} onClick={()=>setDetail(detail===w.id?null:w.id)}>{detail===w.id?'Thu gọn':'Xem ví dụ'}</button></div>{detail===w.id&&<div className="word-example"><p lang={locale[language]}>{w.example.text}</p>{w.example.reading&&<small>{w.example.reading}</small>}<p>{w.example.meaning}</p><button className="text-button" onClick={()=>speak(w.example.text,language)}><Volume2 size={16}/>Nghe ví dụ</button></div>}</article>;})}</div>{!visible.length&&<div className="empty-card"><Heart size={30}/><h2>{filter==='favorites'?'Túi từ yêu thích còn trống.':'Chưa tìm thấy từ phù hợp.'}</h2><p>{filter==='favorites'?'Chạm trái tim ở một từ bạn muốn dùng ngoài đời.':'Thử một nghĩa tiếng Việt hoặc chọn tất cả chủ đề.'}</p></div>}</>}
 </>;
}

function WordGame({words,language,busy,speak,onExit,onFinish}:{words:Vocabulary[];language:Lang;busy:boolean;speak:Props['speak'];onExit:()=>void;onFinish:(seconds:number)=>Promise<number|null>}){
 const [phase,setPhase]=useState<'learn'|'play'|'done'>('learn'),[right]=useState(()=>shuffle(words)),[left,setLeft]=useState<string|null>(null),[matched,setMatched]=useState<string[]>([]),[feedback,setFeedback]=useState(''),[started]=useState(()=>Date.now()),[earned,setEarned]=useState(0);
 function match(id:string){if(!left){setFeedback('Chọn một từ ở cột bên trái trước nhé.');return;}if(left===id){setMatched(p=>p.includes(id)?p:[...p,id]);setFeedback('Một cặp đã tìm thấy!');}else setFeedback('Chưa khớp, mình thử một nghĩa khác nhé.');setLeft(null);}
 async function finish(){const xp=await onFinish(Math.min(600,Math.round((Date.now()-started)/1000)));if(xp!==null){setEarned(xp);setPhase('done');}}
 return <div className="word-game"><div className="lesson-toolbar"><button className="text-button" disabled={busy} onClick={onExit}><ChevronLeft size={18}/>Về túi từ</button><span>{languageNames[language]} · không bấm giờ</span></div>
 {phase==='learn'?<><div className="page-heading compact"><div><p className="eyebrow">XEM MẪU TRƯỚC, THỬ NHỚ SAU</p><h1>Làm quen với 5 từ.</h1><p>Cứ nhìn nghĩa và nghe một lần. Bạn được thử lại thoải mái.</p></div></div><div className="game-preview">{words.map(w=><div key={w.id}><div><strong lang={locale[language]}>{w.term}</strong>{w.reading&&<small>{w.reading}</small>}<p>{w.meaning}</p></div><button className="listen-button" aria-label={`Nghe từ ${w.term}`} onClick={()=>speak(w.term,language)}><Volume2 size={18}/></button></div>)}</div><button className="primary exercise-next" onClick={()=>setPhase('play')}>Mình chơi thử <Shuffle size={19}/></button></>:phase==='play'?<><div className="game-heading"><p className="eyebrow">GHÉP TỪ VỚI NGHĨA</p><h1>Tìm những cặp quen.</h1><p>{matched.length}/5 cặp · chạm một từ, rồi chọn nghĩa tiếng Việt.</p></div><div className="pair-grid"><div>{words.map(w=><button key={w.id} className={'pair-tile'+(matched.includes(w.id)?' matched':left===w.id?' selected':'')} disabled={matched.includes(w.id)||busy} aria-pressed={left===w.id} aria-label={`Chọn từ ${w.term}`} onClick={()=>{setLeft(w.id);setFeedback('');}}><span lang={locale[language]}>{w.term}</span>{w.reading&&<small>{w.reading}</small>}{matched.includes(w.id)&&<Check size={18}/>}</button>)}</div><div>{right.map(w=><button key={w.id} className={'pair-tile meaning-tile'+(matched.includes(w.id)?' matched':'')} disabled={matched.includes(w.id)||busy} aria-label={`Chọn nghĩa ${w.meaning}`} onClick={()=>match(w.id)}>{w.meaning}{matched.includes(w.id)&&<Check size={18}/>}</button>)}</div></div><p className="pair-feedback" role="status">{feedback||'Không mất điểm hay lượt chơi khi ghép chưa đúng.'}</p>{matched.length===5&&<button disabled={busy} className="primary exercise-next" onClick={()=>void finish()}>{busy?'Đang lưu…':'Hoàn thành · lưu 5 từ'}<Check size={18}/></button>}</>:<section className="exercise-card completion-card"><span className="completion-symbol"><Check size={40}/></span><p className="eyebrow">ĐÃ LƯU LƯỢT CHƠI</p><h1>Túi từ thêm một chút.</h1><p>Bạn đã gặp 5 từ. Từ mới có lịch ôn ngày mai; từ đã luyện giữ lịch ôn riêng của bạn.</p><div className="reward-pill">{earned?`+${earned} XP`:'Đã ghi nhận lượt luyện thêm'}</div><p className="muted">Lượt chơi đầu mỗi ngôn ngữ trong ngày có 5 XP. Luyện thêm vẫn có ích.</p><button className="primary exercise-next" onClick={onExit}>Xong cho lúc này <Check size={18}/></button></section>}
 </div>;
}
